USE Customer_behavior;
SELECT * FROM customer_data;


--Q1 what is total revenue generated by male vs female ?
SELECT gender,SUM(purchase_amount) AS Revenue
FROM customer_data
GROUP BY gender;


--Q2 Which Customers used discount but still more than the average?
SELECT customer_id,purchase_amount FROM customer_data
where discount_applied='Yes' and purchase_amount>= (SELECT Avg(purchase_amount) FROM customer_data);


--Q3 Which are the top 5 products with the highest average review rating ?
SELECT TOP 5 item_purchased,ROUND(AVG(review_rating),2) AS "Average review rating"
FROM customer_data
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC;


--Q4 Compare the average purchase amounts between standard and express shipping
SELECT shipping_type,AVG(purchase_amount) AS "Average of purchase" FROM customer_data
WHERE shipping_type in('Express', 'Standard')
GROUP BY shipping_type;


--Q5 DO Subscibed customer spends more ? Compare average spend and total revenue between subscribers and non-subscribers?
SELECT subscription_status,COUNT(customer_id) as "Total count",
ROUND(Avg(purchase_amount),2) AS AVG_SPEND,
ROUND(SUM(purchase_amount),2) AS TOTAL_REVENUE
FROM customer_data
GROUP BY subscription_status
ORDER BY TOTAL_REVENUE,AVG_SPEND DESC;

--Q6 Which 5 products have the highest percentage of purchases with discounts applied ?
SELECT item_purchased,ROUND(100 *SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate
FROM customer_data
GROUP BY item_purchased
ORDER BY discount_rate DESC;


--Q7 Segment customers into New,Returning and Loyal based on their total number of previous purchases and show the count of each segment ?
 with customer_type as(
 SELECT customer_id,previous_purchases,CASE WHEN previous_purchases= 1 THEN 'NEW' WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning' ELSE 'Loyal' 
 END AS customer_segment
 from customer_data
 )
 SELECT customer_segment,COUNT(*) AS customer_count
 FROM customer_type GROUP BY customer_segment;


--Q8 What are the top 3 most purchased products within each category ?
WITH RankedProducts AS (
SELECT category,item_purchased,purchase_amount,ROW_NUMBER() OVER (PARTITION BY category ORDER BY purchase_amount DESC) as rank
    FROM customer_data
)
SELECT category,item_purchased,purchase_amount
FROM RankedProducts
WHERE rank <= 3;


--Q9 Are customers who are repeat buyers (more than 5 previous purchased) also likely to subscribe ?
SELECT subscription_status,
count (customer_id) as repeat_buyers
from customer_data
where previous_purchases > 5
Group by subscription_status


--Q10 What is the revenue contribution of each group ?
SELECT age_group,SUM(purchase_amount) AS total_revenue
FROM customer_data 
GROUP BY age_group
ORDER BY total_revenue DESC;


